FROM google/cloud-sdk

MAINTAINER Anthony Poschen <zanven42@gmail.com>

EXPOSE 8400

ADD /gcd ./gcd

VOLUME /data
ENTRYPOINT ["/gcd/gcd.sh","start", "-p", "8400","-a","datastore", "/gcd/tmp-dir"]
#ENTRYPOINT ["gcloud","beta","emulators","datastore","start","--project=brainwave-studios","--host-port","datastore:8500","--no-store-on-disk"]
