FROM makuk66/docker-oracle-java7

# Default port for DynamoDB Local
EXPOSE 8000

# Create working space
RUN mkdir /var/dynamodb_wd
WORKDIR /var/dynamodb_wd

RUN wget -O /var/dynamodb_wd/dynamodb_local_latest https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
RUN tar xfz /var/dynamodb_wd/dynamodb_local_latest

ENTRYPOINT ["/usr/bin/java", "-Djava.library.path=.", "-jar", "DynamoDBLocal.jar", "-dbPath", "/var/dynamodb_local"]
CMD ["-port", "8400"]
