# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang

# Copy the local package files to the container's workspace.
ADD . /go/src/zanven42/webfront
ADD ./www /go/src/zanven42/webfront/www
# Build the outyet command inside the container.
# (You may fetch or manage dependencies here,
# either manually or with a tool like "godep".)
RUN go install zanven42/webfront

# Run the outyet command by default when the container starts.
ENTRYPOINT /go/bin/webfront

# Document that the service listens on port 8080.
EXPOSE 8002