# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM scratch

# Copy the local package files to the container's workspace.
ADD ./webfront /
ADD ./www /www


# Run the outyet command by default when the container starts.
ENTRYPOINT ["/webfront"]

# Document that the service listens on port 8080.
EXPOSE 8002